In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../../data_set/2.데이터 클린징/loan_train_quiz_cleaning.csv")
df.head(2)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,0,1,0,0,0,0,5849,0.0,128.0,360.0,1.0,2,1
1,1,1,1,1,0,0,4583,1508.0,128.0,360.0,1.0,0,0

In [4]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [5]:
features = ['Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area'] # 입력 데이터(문제)
label = 'Loan_Status' # 정답

In [7]:
X, y = df[features],df[label]
X # y: 정답

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,1,0,0,0,0,5849,0.0,128.0,360.0,1.0,2
1,1,1,1,0,0,4583,1508.0,128.0,360.0,1.0,0
2,1,1,0,0,1,3000,0.0,66.0,360.0,1.0,2
3,1,1,0,1,0,2583,2358.0,120.0,360.0,1.0,2
4,1,0,0,0,0,6000,0.0,141.0,360.0,1.0,2
...,...,...,...,...,...,...,...,...,...,...,...
609,0,0,0,0,0,2900,0.0,71.0,360.0,1.0,0
610,1,1,3,0,0,4106,0.0,40.0,180.0,1.0,0
611,1,1,1,0,0,8072,240.0,253.0,360.0,1.0,2
612,1,1,2,0,0,7583,0.0,187.0,360.0,1.0,2
613,0,0,0,0,1,4583,0.0,133.0,360.0,0.0,1

In [8]:
df.shape

(614, 13)

In [11]:
# 데이터를 “학습용 / 테스트용”으로 나누는 함수 가져온다.
from sklearn.model_selection import train_test_split

In [12]:
# 80%는 학습, 20% 테스트로 사용
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [14]:
X_train.shape, X_test.shape, len(y_train), len(y_test)

((491, 11), (123, 11), 491, 123)

### 모델 생성 및 학습
* 모델 생성 : 변수 = DecisionTreeClassifier()
* 학습 : 변수.fit(X_train, y_train)
    - 문제와 정답을 알고리즘에 학습
* 예측 : 변수.predict(X_test)
    - 확인용 문제를 predict에 넣으면 정답을 알려준다

In [15]:
from sklearn.tree import DecisionTreeClassifier

In [16]:
dtc = DecisionTreeClassifier() # 모델 생성
dtc.fit(X_train, y_train) #학습

DecisionTreeClassifier()

In [17]:
pred = dtc.predict(X_test) # 20% 학습하지 않은 데이터. 예상 답안 뽑음
pred # 예측값

array([1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1])

In [18]:
print(y_test) # 실제 정답

608    1
162    0
417    0
245    0
25     1
      ..
607    1
323    1
321    1
134    1
160    1
Name: Loan_Status, Length: 123, dtype: int64

In [19]:
from sklearn.metrics import accuracy_score

In [21]:
accuracy_score(y_test, pred) # 정확도(얼마나 정확하게 맞췄나)

0.7235772357723578

In [22]:
df_test = pd.read_csv("../../data_set/2.데이터 클린징/loan_test_cleaning.csv")
df_test.head(3)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,0,1,1,0,0,0,5720,0,110.0,360.0,1.0,2
1,1,1,1,1,0,0,3076,1500,126.0,360.0,1.0,2
2,2,1,1,2,0,0,5000,1800,208.0,360.0,1.0,2

In [23]:
df_test.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area'],
      dtype='object')

In [25]:
f = ['Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area']
X_test = df_test[f]
y_test = dtc.predict(X_test) # 모델이 예측한 결과

In [26]:
df_test.head(2)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,0,1,1,0,0,0,5720,0,110.0,360.0,1.0,2
1,1,1,1,1,0,0,3076,1500,126.0,360.0,1.0,2

In [27]:
y_test

array([1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0])

In [29]:
df_test['Loan_Status'] = y_test # 예측 결과 넣기
df_test.T # 행과열을 뒤집어서 출력

,0,1,2,3,4,5,6,7,8,9,...,357,358,359,360,361,362,363,364,365,366
Loan_ID,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,...,357.0,358.0,359.0,360.0,361.0,362.0,363.0,364.0,365.0,366.0
Gender,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,...,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0
Married,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0
Dependents,0.0,1.0,2.0,2.0,0.0,0.0,1.0,2.0,2.0,0.0,...,0.0,2.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0
Education,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
Self_Employed,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
ApplicantIncome,5720.0,3076.0,5000.0,2340.0,3276.0,2165.0,2226.0,3881.0,13633.0,2400.0,...,2500.0,3132.0,4000.0,8550.0,2269.0,4009.0,4158.0,3250.0,5000.0,9200.0
CoapplicantIncome,0.0,1500.0,1800.0,2546.0,0.0,3422.0,0.0,0.0,0.0,2400.0,...,0.0,0.0,2667.0,4255.0,2167.0,1777.0,709.0,1993.0,2393.0,0.0
LoanAmount,110.0,126.0,208.0,100.0,78.0,152.0,59.0,147.0,280.0,123.0,...,60.0,76.0,152.0,96.0,99.0,113.0,115.0,126.0,158.0,98.0
Loan_Amount_Term,360.0,360.0,360.0,360.0,360.0,360.0,360.0,360.0,240.0,360.0,...,360.0,360.0,360.0,360.0,360.0,360.0,360.0,360.0,360.0,180.0
Credit_History,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Property_Area,2.0,2.0,2.0,2.0,2.0,2.0,1.0,0.0,2.0,1.0,...,2.0,0.0,1.0,2.0,1.0,2.0,2.0,1.0,0.0,0.0
Loan_Status,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0

In [30]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [31]:
df_drop = df.drop(columns=['Loan_ID','Loan_Status'])
df_drop.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area'],
      dtype='object')

In [32]:
df_test.head(1)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,0,1,1,0,0,0,5720,0,110.0,360.0,1.0,2,1

In [34]:
# 모델이 학습할 때 사용한 컬럼 구조에 맞춰서 입력 데이터를 만든 것
userInput = pd.DataFrame([[1,1,0,0,0,5720,0,110.0,360.0,1.0,2]], columns=df_drop.columns)
userInput

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,1,1,0,0,0,5720,0,110.0,360.0,1.0,2

In [37]:
dtc.predict(userInput)[0]

np.int64(1)

In [36]:
if dtc.predict(userInput)[0] == 1:
    print("대출 가능")
else:
    print("대출 불가!!!")

대출 가능