### 시계열 데이터
* 시계열 데이터
    - 시간의 흐름에 따라 데이터의 변화를 분석 및 예측하는데 사용되는 데이터
    - 타임스탬프(timestamp) : 특정 시점(시간)을 의미하는 자료형
* 기능
    - to_datetime : 데이터를 시간 자료형으로 변환시켜주는 함수
    - to_period : 날짜 데이터의 년, 월, 일 등을 가져올 수 있다.
        * 옵션
            - freq를 이용하여 각각의 날짜 정보를 얻어올 수 있다
            - freq = A(년), M(월), D(일)
            - D지정시 2020-01-01까지 나오며, M지정시 2020-01, A지정시 2020까지 나온다.
    - Datetimeindex자료형
        * dt객체를 제공하며, dt.year, dt.month, dt.day, dt.hour, dt.minute, dt.second...등을 제공한다
>
* 자세한 정보는 다음 사이트를 참조하기 바란다.
* https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.html

In [2]:
import pandas as pd
dates = ['2026-03-04', '2026-05-05']
df = pd.DataFrame(dates, columns=['date'])
df

         date
0  2026-03-04
1  2026-05-05

In [4]:
df.dtypes

date    object
dtype: object

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    2 non-null      object
dtypes: object(1)
memory usage: 148.0+ bytes

In [6]:
df['new_date'] = pd.to_datetime(df['date']) # 데이터를 시간자료형으로 변환환
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      2 non-null      object
 1   new_date  2 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(1)
memory usage: 164.0+ bytes

In [8]:
print(df['new_date'].dt.year)
df['year'] = df['new_date'].dt.year
df['month'] = df['new_date'].dt.month
df['day'] = df['new_date'].dt.day

df

0    2026
1    2026
Name: new_date, dtype: int32

         date   new_date  year  month  day
0  2026-03-04 2026-03-04  2026      3    4
1  2026-05-05 2026-05-05  2026      5    5

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      2 non-null      object
 1   new_date  2 non-null      datetime64[ns]
 2   year      2 non-null      int32
 3   month     2 non-null      int32
 4   day       2 non-null      int32
dtypes: datetime64[ns](1), int32(3), object(1)
memory usage: 188.0+ bytes

In [13]:
data = [1,2,3]
df = pd.DataFrame(data, columns=['data'])
df

   data
0     1
1     2
2     3

In [14]:
def test(num : int) -> int:
    print("test 실행")
    return num * 10

In [16]:
test2 = lambda n : n*100

In [18]:
df['data'].apply(test2)

0    100
1    200
2    300
Name: data, dtype: int64

In [19]:
df['data'].apply(lambda n : n*200)

0    200
1    400
2    600
Name: data, dtype: int64

In [20]:
dates = ['2026-03-04', '2026-05-05']
df = pd.DataFrame(dates, columns=['date'])
df

         date
0  2026-03-04
1  2026-05-05

In [21]:
datetimer = df['date'].apply(lambda x : pd.to_datetime(x))
datetimer.info(), datetimer

<class 'pandas.core.series.Series'>
RangeIndex: 2 entries, 0 to 1
Series name: date
Non-Null Count  Dtype
--------------  -----
2 non-null      datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 148.0 bytes

(None,
 0   2026-03-04
 1   2026-05-05
 Name: date, dtype: datetime64[ns])

In [22]:
df['year']=datetimer.apply(lambda x : x.year)
df['month']=datetimer.apply(lambda x : x.month)
df['day']=datetimer.apply(lambda x : x.day)
df['dayofweek']=datetimer.apply(lambda x : x.dayofweek) #dayofweek: 요일
df

         date  year  month  day  dayofweek
0  2026-03-04  2026      3    4          2
1  2026-05-05  2026      5    5          1

In [23]:
df['month'] = df['month'].apply(lambda x : 1111 if x > 3 else x)
df

         date  year  month  day  dayofweek
0  2026-03-04  2026      3    4          2
1  2026-05-05  2026   1111    5          1

In [26]:
mask = (df['year'] == 2026) & (df['month'] == 1111)
df[(df['year'] == 2026) & (df['month'] == 1111)]

         date  year  month  day  dayofweek
1  2026-05-05  2026   1111    5          1

In [32]:
print(df[mask])
print("-"*20)
df.loc[mask, 'dayofweek'] = df[mask]['dayofweek'].apply(lambda x : 111 if x == 1 else x)
df

         date  year  month  day  dayofweek
1  2026-05-05  2026   1111    5        111
--------------------

         date  year  month  day  dayofweek
0  2026-03-04  2026      3    4          2
1  2026-05-05  2026   1111    5        111

In [34]:
df_test = df[['date','year']]
df_test

         date  year
0  2026-03-04  2026
1  2026-05-05  2026

In [40]:
df_test = df_test.to_dict('list') # list 형식으로 만듬
df_test

{'date': ['2026-03-04', '2026-05-05'], 'year': [2026, 2026]}

In [41]:
df_date = df_test['date']
print(df_date)
df_year = df_test['year']
print(df_year)

['2026-03-04', '2026-05-05']
[2026, 2026]

In [42]:
for i in range(len(df_year)): # i=0, i<2, i++
    print(df_year[i],":", df_date[i])

2026 : 2026-03-04
2026 : 2026-05-05